version: '{build}'
os: Windows Server 2012
shallow_clone: true
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt\sbt\bin\sbt.cmd" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.11/sbt-0.13.11.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-Xmx4g
build_script:
  - sbt clean +compile
test_script:
  - sbt +test
cache:
  - C:\sbt\
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/4aa4132de72201e17062
    on_build_failure: true
